ALTER TABLE item_vehicle_compatibility RENAME CONSTRAINT item_motorcycle_compatibility_item_id_fkey TO item_vehicle_compatibility_item_id_fkey;
ALTER TABLE item_vehicle_compatibility RENAME CONSTRAINT item_motorcycle_compatibility_item_id_motorcycle_model_id_y_key TO item_vehicle_compatibility_item_id_vehicle_model_id_year_key;
ALTER TABLE item_vehicle_compatibility RENAME CONSTRAINT item_motorcycle_compatibility_pkey TO item_vehicle_compatibility_pkey;
ALTER TABLE vehicle_models RENAME CONSTRAINT motorcycle_models_brand_id_series_model_name_year_start_key TO vehicle_models_brand_id_series_model_name_year_start_key;
ALTER TABLE vehicle_models RENAME CONSTRAINT motorcycle_models_pkey TO vehicle_models_pkey;
