import type { AiRecommendation } from "./pos-types";

export const aiRecommendations: AiRecommendation[] = [
  {
    id: "ai001",
    customerId: "c001",
    kind: "accessory",
    refId: "s013",
    refName: "Öhlins TTX GP 後避震",
    refPrice: 88000,
    reason: "車主今年已下賽道 3 次（麗寶/大鵬灣），原廠避震接近使用上限",
    confidence: 0.89,
  },
  {
    id: "ai002",
    customerId: "c001",
    kind: "package-card",
    refId: "inspection-5",
    refName: "5 次賽道前檢查卡",
    refPrice: 12000,
    reason: "近 12 個月進賽道 3 次，單次檢查 NT$3,600，買卡省 NT$6,000",
    confidence: 0.92,
    savings: 6000,
  },
  {
    id: "ai003",
    customerId: "c001",
    kind: "service",
    refId: "sv006",
    refName: "氣門間隙檢修",
    refPrice: 18000,
    reason: "里程即將達 30,000km，原廠建議進行",
    confidence: 0.76,
  },
  {
    id: "ai004",
    customerId: "c002",
    kind: "accessory",
    refId: "s016",
    refName: "Multistrada 三箱套組",
    refPrice: 68000,
    reason: "車主近 6 個月搜尋「長途旅行」關鍵字 8 次，尚未購買行李箱",
    confidence: 0.82,
  },
  {
    id: "ai005",
    customerId: "c002",
    kind: "service",
    refId: "sv008",
    refName: "大保養 (15,000km)",
    refPrice: 9000,
    reason: "里程達標，上次保養已逾 6 個月",
    confidence: 0.94,
  },
  {
    id: "ai006",
    customerId: "c004",
    kind: "accessory",
    refId: "s012",
    refName: "Termignoni 全段排氣系統 V4",
    refPrice: 128000,
    reason: "同型號車友升級率 67%，車主曾試乘展示車有興趣",
    confidence: 0.71,
  },
  {
    id: "ai007",
    customerId: "c006",
    kind: "finance",
    refId: "fin-lease-36",
    refName: "36 期零利率分期 (以舊換新)",
    refPrice: 0,
    reason: "車主目前 3 台車，偏好 18 個月內置換，新一代 Panigale 即將發表",
    confidence: 0.68,
  },
  {
    id: "ai008",
    customerId: "c009",
    kind: "accessory",
    refId: "s018",
    refName: "DesertX 越野保險桿",
    refPrice: 22500,
    reason: "車主車輛為 DesertX，IG 發文顯示近期越野使用",
    confidence: 0.85,
  },
  {
    id: "ai009",
    customerId: "c012",
    kind: "insurance",
    refId: "ins-full-coverage",
    refName: "全險升級方案 (含道路救援)",
    refPrice: 12800,
    reason: "車主擁有 2 台車，目前僅投保強制險",
    confidence: 0.73,
  },
  {
    id: "ai010",
    customerId: "c025",
    kind: "package-card",
    refId: "maintenance-9",
    refName: "9 次保養套餐卡",
    refPrice: 24000,
    reason: "車主 3 台車同時養護，單次保養 NT$3,600，買卡單台省 NT$8,400",
    confidence: 0.91,
    savings: 8400,
  },
  {
    id: "ai011",
    customerId: "c023",
    kind: "accessory",
    refId: "s020",
    refName: "碳纖維前土除",
    refPrice: 28500,
    reason: "車主上次購買碳纖維配件反應良好（搖臂護蓋好評 5 星）",
    confidence: 0.79,
  },
  {
    id: "ai012",
    customerId: "c014",
    kind: "accessory",
    refId: "s039",
    refName: "Dainese Carbon 3 短手套",
    refPrice: 8800,
    reason: "車主已購皮衣但尚無短手套，夏季到來",
    confidence: 0.81,
  },
];

export function recommendationsFor(customerId: string): AiRecommendation[] {
  return aiRecommendations.filter((r) => r.customerId === customerId);
}

export const splitReceiptPreviewLabels = {
  taxableTitle: "電子發票",
  nonTaxableTitle: "代辦費用收據",
  taxableNote: "統一發票開立後即時上傳財政部",
  nonTaxableNote: "代辦項目 (規費・汽燃費) 以收據列帳",
};
